### ISSUE TITLE
Invalid image tag output

### ISSUE THREAD

**Issue by curtchan** [prestaconcept/PrestaSitemapBundle#173]
In docs; [Decorating Urls](https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/5-decorating-urls.md#nesting)
It is suggested to use relative image src links, this will result in errors in google search console as images' loc tag should be an absolute url to image.

**Comment by curtchan** [comment]
https://github.com/prestaconcept/PrestaSitemapBundle/blame/master/Resources/doc/5-decorating-urls.md#L35-L40

This is the part i'm talking about. Doing as suggested in docs (no absolute url, just relative path to server root directory) will result in relative urls being added into sitemap. Unless i'm missing something, but i went through all docs and haven't seen any note about it.

Passing RequestStack and doing `getSchemeAndHttpHost` on master request solves issue, but i'm not even sure if that's a proper way to do it.

**Comment by yann-eugone** [comment]
Ok, I understand what you mean.
I agree with you, the documentation must show something better than that.

The thing is that the code should work in both web & cli environments.
So, rely `RequestStack` may not be sufficient.

Example, from [Symfony Twig Bridge](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Extension/HttpFoundationExtension.php#L58) .
The `generateAbsoluteUrl` method is using both `RequestStack` and `RequestContext` to achieve it's goal.

An other possible solution could be to use the `UrlGeneratorInterface` to generate an absolute URL to your homepage, then concatenate your asset absolute path to it...

It will be hard to present all these solutions in the documentation.
Maybe we can just update the docs, presenting absolute URLs instead of absolute paths, and add a warning note.

What do you think ?

**Comment by curtchan** [comment]
Presenting absoulte paths might be enough to describe the use-case. When i first saw the docs, i just thought to myself that the base domain url will be preppended to asset path, or it will be taken somehow from decorated Url object. Nonetheless it would be good to have it simply described, maybe extra docs page added, just for Images with information on how to retrieve/generate absolute Urls.

Will try few approaches and maybe there will be some simple way to do it. Also i tried using urlgeneratorinterface, but again, it requires that you have homepage defined, and many people might have it defined with other `name`, etc. so it might be somewhat confusing as well.

**Comment by kiler129** [comment]
To add more to this issue: in a lot of cases you will actually not use (nor should!) the `generateAbsoluteUrl()` but actually the assets module. 

Properly, to avoid WTFs from other devlopers, you should rather inject `\Symfony\Component\Asset\Packages` and call `$this->assets->getUrl(.....)` with your path. That way if someone configures CDN for example it will work across the board (including templates AND the sitemap).

**Comment by yann-eugone** [comment]
The documentation was updated to show only absolute URLs.
A note was also added, encouraging developers to only use absolute URLs.
