### ISSUE TITLE
Bump php to 8.4 and Symfony to 7.2 in tests

### ISSUE THREAD

**Issue by tacman** [prestaconcept/PrestaSitemapBundle#350]
Both PHP and Symfony had releases last month.  The test matrix doesn't yet reflect php 8.4 and Symfony 7.2

I wonder, though, what the test matrix should support.  Symfony 7.0 is at EOL, and 5.4 is on security-fixes only.  PHP 8.0 is also EOL.

https://symfony.com/releases#symfony-releases-calendar

For example, right now this bundle supports 6.0, in composer.json all the symfony bundles are ^5.4||^6.0||^7.0, I think it'd be better as "^5.4||^6.4||^7.1" and have the tests reflect that.  But I'm not sure.  I brought it up as [a discussion](https://github.com/symfony/symfony/discussions/58979) with the Symfony devs, but I'm still not sure.

In version 5 of this bundle, if you drop 5.4 and only support 6.4+, you can refactor the DI and move a lot of the config code into the Bundle class itself by extending AbstractBundle.  If it's only 8.2 (or 8.3)+, then of course you can take advantage of all the static code tools that those releases support.

**Comment by yann-eugone** [comment]
We slowly remove old PHP + Symfony versions while incrementing versions of this bundle
But there is no reason to say "we are not compatible with symfony 6.0, if we say we are compatible with symfony 5.4"
The testing matrix on the other hand is testing the "most used" versions, which are LTS and latest versions
We are not always up to date on the latest version, because it is PITA to think about every bundle on every organization each of us are managing
I know I'm late here, but a PR will come soon (and no version will be dropped in the process)
