### ISSUE TITLE
Caching with Redis through snc/redis-bundle

### ISSUE THREAD

**Issue by apheleia** [prestaconcept/PrestaSitemapBundle#66]
Is it possible to cache the sitemaps using the `snc/redis-bundle`? We do DB (and other) caching using that bundle instead of the `doctrine-cache` bundle.

**Comment by yann-eugone** [comment]
Let's try to think about an abstraction layer of cache, which can had an implementation with anything you need.

At least : 

- doctrine/doctrine-cache-bundle
- snc/redis-bundle

Anything else ?

**Comment by yann-eugone** [comment]
This will be done in the next major release. See #92.
I'm closing this issue.

**Comment by apheleia** [comment]
Great, thanks :heart:

**Comment by yann-eugone** [comment]
@apheleia I did take a look today during the refactoring, this is already possible to use redis as cache layer, since the [LiipDoctrineCacheBundle](https://github.com/liip/LiipDoctrineCacheBundle) rely on [doctrine/cache](https://github.com/doctrine/cache) and this library has : 

- [PredisCache](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/PredisCache.php)
- [RedisCache](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RedisCache.php)

did you try to configure it ?

**Comment by yann-eugone** [comment]
Closing, since DoctrineCacheBundle will be integrated in #105 and it supports redis client
