### ISSUE TITLE
Prepare 2.0

### ISSUE THREAD

**Issue by nicolas-bastien** [prestaconcept/PrestaSitemapBundle#92]
As this bundle is pretty old we need to refactor it and prepare a 2.0 release.

In this issue we will plan all the main changes we want to put in it.

Community is more than welcome to share their idea.

Lead developer for this release will be @yann-eugone

**Comment by yann-eugone** [comment]
### Situation

- The Bundle is doing the job well
- We had some difficulties making the Bundle evolve (Symfony 2.1, PHP 5.3, issues opened 3 years ago...)
- There is lot of issues, caused by it's lack of flexibility
- The Bundle lack of tests
- Core team is not part of Prestaconcept anymore

### Conclusion

We need a new major version. Why ?

- We still believe in this Bundle and we hope the community still want us to improve it
- The code itself is not ready to evolve as we/you need
- We need to build a new team around this bundle, and this team has to trust/believe the code

### Solution

So far the bundle has to few components, and to few abstractions.
First thing is to write a more flexible code structure.

What is this all about : generating site maps (thank you captain ^^)

How do we do that : 
- **Collecting** sitemap nodes (as POPO) around the whole application
- *Optionnaly* **Store** the result somewhere
- **Serializing** these nodes to an XML file
- *Optionnaly* **Store** the file somewhere
- Serve the file

To me, each step must have its own dedicaded component, with less responsability and a dedicated interface for it : 

### SitemapCollectorInterface

Many instances for each application.
The responsability of this component is to collect (some way) node elements and add it to the sitemap.

Examples : 
- Triggering an event to the Symfony's [EventDispatcher component](http://symfony.com/doc/current/components/event_dispatcher/introduction.html)
- Using Symfony's [Routing component](http://symfony.com/doc/current/components/routing/introduction.html) to extract routes configured to be added
- *your need here...*

### SitemapNodeStorageInterface

Single instance for each application.
The reponsability of this component is to store (some way) collected node elements to avoid re-trigerring the collect.

Examples : 
- Using a provider from [DoctrineCacheBundle](https://github.com/doctrine/DoctrineCacheBundle)
- Using a client from [SncRedisBundle](https://github.com/snc/SncRedisBundle)
- *your need here...*

### SitemapSerializerInterface

Single instance for each application.
The reponsability of this component is to serialize (some way) collected (or stored) node elements as an XML string.

Examples : 
- Using a dedicated component that will re-use current rules
- Using the Symfony's [Serializer component](http://symfony.com/doc/current/components/serializer.html)
- *your need here...*

### SitemapFileStorageInterface

Single instance for each application.
The reponsability of this component is to store (some way) XML serialized sitemap to avoid re-serializing it.

Examples : 
- Using a provider from [DoctrineCacheBundle](https://github.com/doctrine/DoctrineCacheBundle)
- Using a client from [SncRedisBundle](https://github.com/snc/SncRedisBundle)
- *your need here...*

If everyone agree with this king a refactoring, I will take some time to implement it.

**Comment by yann-eugone** [comment]
@esion @alain-flaus @Koc it would be appreciated if somone can provide some complex sitemap examples make sure we don't break anything during the refactoring

**Comment by Koc** [comment]
I think that has no sense depends on https://github.com/snc/SncRedisBundle or https://github.com/doctrine/DoctrineCacheBundle . Just add dependency to https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/Cache.php interface. Especially if we want extract Sitemap component from bundle for getting possibility use it in thirdparty projects like Silex/Laravel/etc

**Comment by yann-eugone** [comment]
@Koc I don't intend to depend on any third-party bundle/library. Everything will be registered as a suggest.
In fact, this is what the rework is all about, the core component will not rely on third party components, but on adapters.
We can add the component/bundle split to the roadmap of the 2.0 (now or never to me), but I'm not familiar with Silex/Laravel or other things, I cannot provide support for these frameworks.

**Comment by nicolas-bastien** [comment]
@yann-eugone if we make a component any body can use it at standalone and we don't have to care if it's Lavarel, zend, drupal.....

they will have to make their own abstraction to use it like we do with a bundle in sf.

So as you said now or never, I would suggest now ?

**Comment by Koc** [comment]
@nicolas-bastien are right, I propose split sitemap generation from integration with Symfony. Make framework-agnostic library which uses `symfony/{event-dispatcher,console,filesystem}`

**Comment by Koc** [comment]
>  *Collecting* sitemap nodes (as POPO) around the whole application
>  *Serializing* these nodes to an XML file

I think that collecting+serializing is wouldn't work on really big sitemaps. For example we have sitemap with 22 parts (50k urls per part). For what do you want to store them? Why not just dump as now?

**Comment by yann-eugone** [comment]
@Koc but this is done already, but the serialization is done in the POPO (toXml method)...

**Comment by yann-eugone** [comment]
@esion @alain-flaus @Koc please see https://github.com/prestaconcept/Sitemap/issues/3

**Comment by yann-eugone** [comment]
abandonned

**Comment by Koc** [comment]
@yann-eugone a lot of referenced issues in this issue was closed. Shouldn't they to be reopened?

**Comment by yann-eugone** [comment]
@Koc yes we should reopen everything.

**Comment by Koc** [comment]
@yann-eugone why 2.0 closed? because lack of activity?

**Comment by yann-eugone** [comment]
seriously speaking ?
i opened the component several monthes ago, asked all of you for a review, and nothing happened, so i decided to stop it

**Comment by iamdey** [comment]
I do not use sitemap bundle anymore (I do not write PHP anymore).

My 2 cents:

>Situation
>
>    The Bundle is doing the job well

So yes, probably too much effort to go further.

**Comment by yann-eugone** [comment]
it's fine to me, i just want to clear the situation in this bundle so everybody can keep using it
